# Display
screen_scale = 2.0
compositor_mode = "surface"

# Theme
cursor_size = 24
font_family = "Inter"
cursor_theme = "Notwaita-Black"
theme_scheme = "Light"
background_image = "../resources/backgrounds/zach3.jpg"

# Inputs
keyboard_repeat_delay = 300
keyboard_repeat_rate = 30
natural_scroll = true


# Dock
genie_scale = 0.5
genie_span = 10.0

# Apps
terminal_bin = "weston-terminal"
file_manager_bin = "dolphin"
browser_bin = "google-chrome-stable"
browser_args = [""]

[displays.named."winit"]
resolution = { width = 1280, height = 1000 }
refresh_hz = 60.0
position = { x = 0, y = 0 }

# Keyboard remapping
[modifier_remap]
logo = "ctrl"
ctrl = "logo"

#[key_remap]
# "BackSpace" = "Delete"

[keyboard_shortcuts]
"Ctrl+Delete" = "Quit"
# "Ctrl+Shift+Q" = "Quit"
"Ctrl+Return" = { run = { cmd = "terminator", args = [] } }
"Logo+Space" = { open_default = "file_manager" }
"Logo+B" = { open_default = "browser" }
"Ctrl+1" = { builtin = "Workspace", index = 0 }
"Ctrl+2" = { builtin = "Workspace", index = 1 }
"Ctrl+3" = { builtin = "Workspace", index = 2 }
"Ctrl+4" = { builtin = "Workspace", index = 3 }
"Logo+Shift+M" = "ScaleDown"
"Logo+Shift+P" = "ScaleUp"
"Logo+Shift+R" = "RotateOutput"
"Logo+Shift+I" = "RunLayersDebug"
"Alt+ArrowUp" = "ToggleMaximizeWindow"
"Ctrl+Tab" = "ApplicationSwitchNext"
"Ctrl+Shift+Tab" = "ApplicationSwitchPrev"
"Ctrl+`" = "ApplicationSwitchNextWindow"
"Ctrl+Q" = "ApplicationSwitchQuit"
"Ctrl+ArrowUp" = "ToggleMaximize"
#"Ctrl+W" = "CloseWindow"
#"Ctrl+Shift+W" = "CloseWindow"
"Ctrl+D" = "ExposeShowDesktop"
"0" = "ExposeShowAll"
"Ctrl+$" = "SceneSnapshot"

[dock]
bookmarks = [
  { desktop_id = "files.desktop" },
  { desktop_id = "code.desktop" },
  { desktop_id = "gedit.desktop" },
  { desktop_id = "google-chrome.desktop" },
  { desktop_id = "terminator.desktop" },
  { desktop_id = "ghostty.desktop" },
  { desktop_id = "com.obsproject.Studio.desktop" },
  { desktop_id = "kitty.desktop" },
]
