[package]
name = "hello-layers"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31"
wayland-backend = "0.3"
wayland-protocols = { version = "0.32", features = ["client"] }
wayland-scanner = "0.31"
tempfile = "3"
